name: customer_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  get: 4.6.1
  get_storage: ^2.0.3
  intl: ^0.17.0
  rename: 2.0.1
  google_sign_in: 5.3.2
  firebase_core: 1.17.1
  firebase_auth: 3.3.19
  lottie: 1.3.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/lottie/
    - assets/logo/
  uses-material-design: true

