name: customer_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  carousel_indicator: ^1.0.6
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  dropdown_search: 0.6.3
  firebase_auth: 3.3.19
  firebase_core: ^1.19.2
  firebase_messaging: ^12.0.0
  cloud_firestore: ^3.3.0
  firebase_storage: ^10.3.2
  flutter_local_notifications: ^9.7.0
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.0
  form_field_validator: ^1.1.0
  get: 4.6.1
  get_storage: ^2.0.3
  google_sign_in: 5.3.2
  http: ^0.13.4
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  introduction_screen: ^3.0.2
  lottie: 1.3.0
  photo_view: ^0.14.0
  rename: 2.0.1
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/logo/
  uses-material-design: true
